services:
  postgres:
    image: postgres:17
    container_name: snip-link-db
    environment:
      POSTGRES_DB: snip-link-db
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - postgres_data:/bitnami/snip-link-db
    ports:
      - "5432:5432"

volumes:
  postgres_data:
