[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = [
  "cd apps/api && bun run db:generate",
  "cd apps/web && bun run build"
]

[start]
cmd = "bun run start:railway"